#import "../../../utils.typ": *
#import "../_variables.typ": *

#proof()[
  (finite-horizon case)

  _Adapted from Sutton and Barto @sutton_reinforcement_2018. _

  We aim to compute the gradient of the expected return $J(theta) = EE_(tau~pi_theta) [R(tau)]$, where $tau = (s_0, a_0, r_0, dots, s_T)$ is a trajectory generated by the policy $pi_theta$ and $R(tau)$ its return.
  Using the log-derivative trick, we write:
  $
    nabla_theta J(theta) & = nabla_theta EE_(tau~pi_theta) [R(tau)] \
    & = EE_(tau~pi_theta) [R(tau) nabla_theta log p(tau; theta)].
  $
  The trajectory probability under policy $pi_theta$ is:
  $
    p(tau; theta) =
    rho(s_0) product_(t=0)^(T-1)
    pi_theta (a_t | s_t) P(s_(t+1) | s_t, a_t),
  $
  where $rho(s_0)$ is the initial state distribution, and $P(s_(t+1) | s_t, a_t)$ are the #acr("MDP")'s transition dynamics.
  As they are both independent of $theta$, the log of the trajectory probability simplifies to:
  $
    log p(tau; theta) =
    sum_(t=0)^(T-1) log pi_theta (a_t | s_t) + "const".
  $
  Taking the gradient:
  $
    nabla_theta log p(tau; theta) =
    sum_(t=0)^(T-1) nabla_theta log pi_theta (a_t | s_t).
  $

  We substitute back into the gradient of the objective:
  $
    nabla_theta J(theta) & = EE_(tau~pi_theta) [
                             R(tau) sum_(t=0)^(T-1) nabla_theta log pi_theta (a_t | s_t)
                           ] \
                         & = sum_(t=0)^(T-1) EE_(tau~pi_theta) [
                             nabla_theta log pi_theta (a_t | s_t)
                             R(tau)
                           ]
  $
  Since the return $R(tau)$ is constant for all time steps, we can reduce variance by using the time-dependent return $G_t = sum_(k=0)^(T-t) gamma^k r_(t+k)$ starting at time $t$, as proposed in REINFORCE @williams_simple_1992:
  $
    nabla_theta J(theta)
    = sum_(t=0)^(T-1) EE_(tau~pi_theta) [
      nabla_theta log pi_theta (a_t | s_t) G_t
    ]
  $

  This is the REINFORCE estimator, which gives an unbiased estimate of the policy gradient @williams_simple_1992.
  Finally, this expectation can be rewritten in terms of the stationary distribution $d_(pi_theta) (s)$, yielding the result:
  $
    nabla_theta J(theta)
    = EE_(s~d_(pi_theta), a ~ pi_theta) [
      nabla_theta log pi_theta (a | s) #q-pi-theta (s, a)
    ]
  $
]
