#import "/utils.typ": *

== Outline and Contributions

This thesis explores how deep learning can be leveraged to enhance acoustic perception in robotics, with a focus on sound source localization and navigation tasks driven by auditory input.
The contributions are centered around the development of tools and learning-based methods that enable social robots to operate more effectively in complex, reverberant environments using audio alone.
The research is articulated across four technical chapters, each addressing a distinct sub-problem: from simulation and signal modeling to supervised perception and reinforcement learning.
All contributions are supported by original software implementations and extensive experimentation.


=== A Modular Simulation Platform for Robotic Acoustic Learning

The first core contribution is the development of a custom acoustic simulation platform (@chap:simulator).
We introduce a flexible and feature-rich simulation framework for acoustic robotics, developed as a foundational tool for the research conducted in this thesis.
Modern deep learning methods—particularly in #acr("SSL") and #acr("DRL")—require large-scale data that is difficult to acquire through physical experimentation.
To address this, we designed a modular simulator that generates realistic multi-channel audio recordings in virtual rooms.
The simulator supports customizable microphone arrays, varied source types (speech, noise), and dynamic trajectories for both sources and receivers.
It integrates two back-end RIR simulation engines: the feature-rich but slower _Pyroomacoustics_ @scheibler_pyroomacoustics_2018, and the high-performance GPU-accelerated _gpuRIR_ @diaz-guerra_gpurir_2021 library.
Additional layers of abstraction were developed to model robot movement, generate egocentric acoustic features, and simulate realistic interaction scenarios in a step-based pipeline.
A novel method was introduced to bootstrap reverberation across short simulation steps, allowing accurate modeling of reverberant tails during dynamic agent movement.
This simulator, released as open-source research software, is used throughout the thesis for dataset generation, training supervision, and interactive policy evaluation.


=== Learning-Based Sound Source Localization in Static Settings

Static sound source localization is the focus of @chap:ssl, where we examine how deep learning can address this fundamental challenge in speech-based auditory perception.
We begin with a focused literature review of this fundamental signal processing task, covering both classical methods and recent deep learning-based approaches.
The chapter then explores two deep learning-based localization pipelines developed and tested using synthetic datasets generated by our simulator.

In the single-source setting, a convolutional neural network is trained to estimate the #doa of a speech source based on interaural features (ILD and IPD).
We evaluate the model across several microphone array layouts and signal representations, showing how design choices—such as array geometry, microphone directivity, and feature pre-processing—impact performance.
This analysis offers practical insights into building accurate, low-latency #acr("SSL") models using compact hardware setups.

The multi-source formulation extends the problem to scenarios with an arbitrary number of active speakers.
An angular spectrum representation is adopted, framing #acr("SSL") as a continuous regression task.
A dedicated convolutional architecture is implemented and trained on a large synthetic dataset, with performance evaluated using both fixed and variable source counts.
Inspired in part by prior work @he_neural_2021, the pipeline was reimplemented, adapted, and integrated into our experimental framework.
Additional contributions include a detailed ablation study on source proximity, context length, and alternative loss formulations.

Together, these experiments establish robust and reproducible baselines for #acr("SSL") in complex environments, forming a foundation for the dynamic and interactive extensions developed in the next chapters.


=== Active Sound Source Localization through Temporal Aggregation

@chap:active_ssl addresses the task of #acr("ASSL"), in which a robot accumulates auditory observations over time as it moves through an environment.
Building on the multi-source #acr("SSL") model developed in @chap:ssl, we propose a method that aggregates directional information from short audio segments recorded at different positions along a trajectory.
The key idea is to construct and refine an egocentric 2D likelihood map of source positions by combining #acr("SSL") predictions from multiple time steps.
Two aggregation strategies are explored: a naive averaging approach and a learned blending network based on a U-Net architecture.
The final source positions are extracted via a spatial clustering algorithm (DBSCAN), enabling the system to handle an arbitrary number of concurrent speakers.
Experiments reveal the critical role of trajectory length (horizon), feature resolution, and the quality of the upstream #acr("SSL") model in determining localization accuracy.
While the method is constrained to static sources, it demonstrates that spatial reasoning can be significantly improved by leveraging motion—even in the absence of ground-truth robot positions or multimodal sensing.


=== Perceptually Guided Navigation via Deep Reinforcement Learning

@chap:rl shifts focus from passive perception to active decision-making, exploring how #acr("DRL") can be used to optimize robotic behavior in acoustically complex environments.
The chapter begins with a comprehensive introduction to reinforcement learning, outlining its conceptual foundations, historical development, and mathematical formulation.
It provides detailed explanations of policy gradient methods, and focuses on the #acr("PPO") algorithm used throughout the work.
This overview is designed to make the chapter self-contained and accessible to readers with varying levels of prior experience in #acr("RL").

Building on this theoretical grounding, we introduce a novel sound-driven navigation task in which a robot must reposition itself in a reverberant environment to optimize #acr("ASR") performance.
The task is formalized as a #acr("POMDP"), where the agent receives only multi-channel audio input and is rewarded based on the Word Error Rate (WER) achieved by a downstream #acr("ASR") model.
A full training pipeline is implemented using the PPO algorithm, with a custom neural architecture and an environment built on our simulator.
The agent’s perception module reuses a convolutional feature extractor pretrained in a supervised setting on the single-source localization task introduced in @chap:ssl.
This enables it to ground its navigation policy in spatial auditory cues.
Observations are encoded as interaural spectral features (ILD and IPD), and the reward signal is provided by a pre-computed #acr("WER") map evaluated on real #acr("ASR") transcripts.

Experiments show that the learned policy reliably improves #acr("ASR") performance by navigating toward acoustically favorable positions, even without access to visual or geometric cues.
The contribution demonstrates how auditory perception can be cast as a reward optimization problem and illustrates the potential of #acr("DRL") to produce interpretable, perception-driven navigation strategies.
It also establishes a flexible and reproducible framework for future work on learning-based auditory control.


=== Scope, Methodology, and Implementation Context

A deliberate constraint throughout the thesis is the exclusive use of acoustic sensing.
While audio is often used in combination with vision or depth sensing in robotics, this work focuses solely on microphone-based input to explore how far auditory perception alone can be pushed.
This makes the learning tasks harder but also more focused, and aligns with biological inspiration—many animals rely heavily on hearing for navigation and interaction.
This constraint also emphasizes the contribution of the acoustic simulation platform, which enables the creation of large, diverse datasets without relying on costly visual modeling.

The entire research pipeline—simulator, datasets, models, training routines, and evaluation tools—was developed from scratch as part of this thesis.
No pre-existing codebase was forked or extended.
Instead, each module was built to fit within a coherent ecosystem.
This reflects a dual contribution: a set of scientific results in deep learning for robotic audition, and a reproducible software foundation for future research in the field.