#import "/utils.typ": *

=== Deep Reinforcement Learning
<sec:rl:intro:deep_reinforcement_learning>

Although #acr("RL") has existed since the 1970s, it has experienced a more recent and considerable surge in popularity @arulkumaran_deep_2017.
As supervised learning and the machine learning field in general, #acr("RL") has benefited from the possibilities offered by Deep Neural Networks.
Traditionally, #acr("RL") leveraged simpler methods such as tabular methods @watkins_learning_1989 @sutton_learning_1988, linear function approximators, or shallow neural networks @barto_neuronlike_1983 @tesauro_temporal_1995.
The main problem of those approaches for policy modeling is their limited capacity to handle larger state and action spaces.
Hence, #acr("RL") has been mainly limited to low-dimensional problems @arulkumaran_deep_2017.
As #acrpl("MDP")s become more intricate, the memory, computation, and, more importantly, sample complexities grow significantly.
#acrpl("DNN")s offer a capable scaling method and have been successfully used as function approximators @arulkumaran_deep_2017 @wang_deep_2024.

The first applications of artificial neural networks to #acr("RL") occurred in the 1990s.
For instance, the popular REINFORCE algorithm by Williams @williams_simple_1992 employed a shallow network that is optimized using gradient descent.
However, the major success awaited Deep Learning's boom of the 2010s.
Mnih et al. @mnih_playing_2013 have famously demonstrated the capacity of those more modern models.
They combined Watkins' Q-value algorithm @watkins_learning_1989 with a deep convolutional neural network.
To showcase the capabilities of their method, the authors tackled seven Atari 2600 games from the Arcade Learning Environment @bellemare_arcade_2013.
Performance surpassed existing benchmarks and, notably, human performance in six games.
This work acted as a foundation for the entire #acr("RL") domain and started the highly dynamic era of #acr("DRL").
Since then, larger and larger networks have been combined with advances made in algorithmic aspects.

Nevertheless, scaling #acr("DRL") models up requires significant amounts of training data.
This translates into the need for environments that can provide tens of thousands of interactions at a tractable cost.
Mnih et al. used around 10 million frames of each game to train their #acr("DQN") agents.
The OpenAI Five @berner_dota_2019 project consists of training an agent to play the game Dota 2.
In total, their agent has played for an approximate duration of 180 years.
Similarly, when applying #acr("DRL") to autonomous driving, collecting a high amount of interactive experience is necessary to achieve decent performance.
Bansal et al. @bansal_chauffeurnet_2018 have used a dataset of 30 million samples to train their policy.
They stated that their initial attempts at imitation learning on this data were unsuccessful.
Finally, it required more advanced techniques to train a working system.


*Games.*
Board or video games are suitable candidates for #acr("DRL") techniques.
Video games are intrinsically operated virtually; board games can easily be transposed to computer programs.
This convenient property allows for scalable training data generation.
Contrary to applications in robotics, they do not require any special transfer techniques to a real target environment.
Also, some games are, by nature, easy, constrained problems in which achieving an optimal policy is sometimes easily feasible.
As such, they have been used as toy examples or benchmark tasks to evaluate #acr("RL") algorithms.
The aforementioned Atari benchmark @mnih_playing_2013 provides #acr("RL") environments of varying difficulty.
Regarding board games, the _AlphaGo_ @silver_mastering_2016 and _AlphaZero_ @silver_mastering_2017  models from DeepMind have shown superhuman performance on the challenging game of Go.
While _AlphaGo_ was first trained on human expert games and only later fine-tuned using #acr("RL"), _AlphaZero_ exclusively leveraged self-play to learn the policy.
This is a clear example of how #acr("DRL") can solve complex tasks by exploiting massive amount of interactions with the environment.



*#acr("RLHF").*
Finally, #acr("RLHF") helps turning #acrpl("LLM") into conversational agents @ouyang_training_2022 @bai_training_2022 @deepseek-ai_deepseek-r1_2025.
At first, large-scale auto-regressive models such as GPT-3 @brown_language_2020 are trained on massive datasets in a supervised manner.
Then, human agents interact with the resulting _chat bot_ and express their preferences between several answers generated by the chatbot.
These preference expressions are used to generate a reward signal.
The initial model then gets fine-tuned using a #acr("DRL") algorithm such as #acr("PPO") @schulman_proximal_2017 to account for the obtained feedback.